version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "staging"
    schedule:
      interval: "daily"

  # Maintain dependencies for backend npm
  - package-ecosystem: "npm"
    directory: "/backend"
    target-branch: "staging"
    schedule:
      interval: "daily"

  # Maintain dependencies for frontend npm
  - package-ecosystem: "npm"
    directory: "/frontend"
    target-branch: "staging"
    schedule:
      interval: "daily"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/"
    target-branch: "staging"
    schedule:
      interval: "daily"
