version: '2'
services:
  backend:
    build: ./backend
    ports:
    - "8081:80"
    volumes:
    - ./backend:/opt/app
    links:
    - mongo
  frontend:
    build: ./frontend
    ports:
    - "8080:80"
    volumes:
    - ./frontend:/opt/app
	links:
    - backend
  mongo:
    image: mongo
    ports:
    - "27017:27017"
  mongoclient:
    image: mongoclient/mongoclient
    ports:
    - "3000:3000"
