version: '2'
services:
  backend:
    build: ./backend
    ports:
    - "${BACKEND_PORT}:8080"
    volumes:
    - ./backend:/opt/app
    - ./log:/opt/log
    links:
    - mongo
    - redis
  frontend:
    build: ./frontend
    ports:
    - "${FRONTEND_PORT}:80"
    volumes:
    - ./frontend:/opt/app
  mongo:
    image: mongo:4.0
    ports:
    - "${MONGO_PORT}:27017"
    command: "--auth"
  mongoclient:
    image: mongoclient/mongoclient
    ports:
    - "${MONGOCLIENT_PORT}:3000"
  redis:
    image: redis
    command: "--notify-keyspace-events Ex --requirepass ${REDIS_PASSWORD}"
    volumes:
    - .redis:/data
    ports:
    - "${REDIS_PORT}:6379"
